---

    - name: Create output directory
      #file: path=/etc/some_directory state=directory mode=0755
      file: path=output state=directory mode=0755

    - name: Create Build Config File
      template: src=java-build.j2 dest=output/java-build.xml

    - name: Create Test Config File
      template: src=java-test-eap.j2 dest=output/java-test-eap.xml

    - name: Create Dev Deploy Config File
      template: src=java-deploy-dev.j2 dest=output/java-deploy-dev.xml

    - name: Create Stg  Deploy Config File
      template: src=java-deploy-stg.j2 dest=output/java-deploy-stg.xml

    - name: Create List View 
      template: src=java-list-view.j2 dest=output/java-list-view.xml

    - name: Create Pipeline View
      template: src=java-pipeline-view.j2 dest=output/java-pipeline-view.xml

    - name: Deploy {{ job_prefix }}-Build
      uri: 
        url: "{{ jenkins_host_url }}/createItem?name={{ job_prefix }}-Build"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-build.xml') }}"

    - name: Deploy {{ job_prefix }}-Test-EAP
      uri: 
        url: "{{ jenkins_host_url }}/createItem?name={{ job_prefix }}-Test-EAP"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-test-eap.xml') }}"

    - name: Deploy {{ job_prefix }}-Deploy-Dev
      uri: 
        url: "{{ jenkins_host_url }}/createItem?name={{ job_prefix }}-Deploy-Dev"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-deploy-dev.xml') }}"

    - name: Deploy {{ job_prefix }}-Deploy-Stg
      uri: 
        url: "{{ jenkins_host_url }}/createItem?name={{ job_prefix }}-Deploy-Stg"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-deploy-stg.xml') }}"

    - name: Deploy {{ jenkins_listview_name }}
      uri: 
        url: "{{ jenkins_host_url }}/createView?name={{ jenkins_listview_name }}"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-list-view.xml') }}"

    - name: Deploy {{ jenkins_pipeline_name }}
      uri: 
        url: "{{ jenkins_host_url }}/createView?name={{ jenkins_pipeline_name }}"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/xml"
        body: "{{ lookup('file', 'output/java-pipeline-view.xml') }}"

    - name: Remove Output Directory
      file: path=output state=absent

