---
    - name: Adding Credentials
      uri:
        url: "{{ jenkins_host_url }}/scriptText"
        force_basic_auth: yes
        user: "{{ pipeline_user }}"
        password: "{{ pipeline_password }}"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: "script={{ lookup('template', 'credentials.groovy.j2') }}"
      tags: creds

    - name: Adding Maven Settings
      uri:
        url: "{{ jenkins_host_url }}/scriptText"
        force_basic_auth: yes
        user: "{{ pipeline_user }}"
        password: "{{ pipeline_password }}"
        method: POST
        return_content: yes
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: "script={{ lookup('template', 'addSettingsFile.groovy.j2') }}"
      tags: creds
