job_prefix: ""
git_url: https://git.example.com/project/project.git
git_branch: ""
git_context: ""
sonar_url: http://sonar.example.com
maven_group_id: ""
maven_artifact_id: ""
maven_pom: pom.xml
maven_build_goals: clean package
maven_test_goals: "clean org.jacoco:jacoco-maven-plugin:prepare-agent test integration-test sonar:sonar -Dsonar.host.url={{ sonar_url }}"
build_child_projects: "{{ job_prefix }}-Deploy-Dev, {{ job_prefix }}-Test-EAP"
downstream_projects: "{{ job_prefix }}-Deploy-Stg"
nexus_repo: http://nexus.example.com/content/repositories/releases/
openshift_user: ""
openshift_password: ""
openshift_server: server.ose.example.com
openshift_dev_project: eap-dev
openshift_stg_project: eap-stg
application_host_url: dev.example.com
dev_application_host_url: stg.example.com
jenkins_listview_name: "{{ job_prefix }}-Jobs"
jenkins_pipeline_name: "{{ job_prefix }}-Pipe"
jenkins_pipeline_jobs: Build,Test-EAP,Deploy-Dev,Deploy-Stg
jenkins_host_url: http://localhost:8080
